sudo: false

language: node_js

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - python-virtualenv

node_js:
- "4"
- "0.10"

cache:
  apt: true
  directories:
  - node_modules

before_script:
- npm prune
- if [ ${TRAVIS_REPO_SLUG} = camptocamp/ngeo ] ; then openssl aes-256-cbc -K $encrypted_66d875d20fac_key -iv $encrypted_66d875d20fac_iv -in secrets.tar.enc -out secrets.tar -d; fi
- if [ ${TRAVIS_REPO_SLUG} = camptocamp/ngeo ] ; then tar xvf secrets.tar; fi
- if [ ${TRAVIS_REPO_SLUG} = camptocamp/ngeo ] ; then cp .transifexrc $HOME/.transifexrc; fi
- if [ ${TRAVIS_REPO_SLUG} = camptocamp/ngeo ] ; then cp ngeo_deploy_key $HOME/.ssh/id_rsa; fi
- if [ ${TRAVIS_REPO_SLUG} = camptocamp/ngeo ] ; then chmod 600 $HOME/.ssh/id_rsa; fi
- git config --global user.name "Travis"
- git config --global user.email "travis@travis-ci.org"

script:
- if [ ${TRAVIS_PULL_REQUEST} != "false" ] ; then git diff --check ${TRAVIS_BRANCH} -- ; fi
- if [ "`git grep @fileoverview src contribs`" != "" ] ; then echo "Using @fileoverview breaks the documentation main page" ; false ; fi
- if [ "`git grep @example src contribs`" != "" ] ; then echo "We don't use @example to have the example in the description" ; false ; fi
- make check
- make .build/examples-hosted/index.html
- make .build/examples-hosted/contribs/gmf/index.html
- make apidoc

after_success:
- 'cat .build/coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls.js'

deploy:
- provider: script
  script: ./deploy_ghpages.sh
  skip_cleanup: true
  on:
    repo: camptocamp/ngeo
    all_branches: true
    node: "0.10"
- provider: script
  script: make transifex-send
  skip_cleanup: true
  on:
    repo: camptocamp/ngeo
    branch: master
    node: "0.10"
